spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/supportportal"
    username: supportportal
    password: supportportal
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
