server:
  port: 8081
  error:
    path: /error
  jetty:
    accesslog:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  trace:
    http:
      enabled: true

spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: password
    initialization-mode: embedded
    platform: h2
  devtools:
    add-properties: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  hibernate:
    hbm2ddl:
      auto: create-drop
    show_sql: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

app:
  corsallowedorigins:
    - http://localhost:3000
    - http://localhost:4200

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
    web: debug
  pattern:
    dateformat: yyy-MM-dd HH:mm:ss SSS

info:
  app:
    name: ^project.name^
    description: ^project.description^
    version: ^project.version^

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  packages-to-scan: net.axelwulff.usermanagement.domain, net.axelwulff.usermanagement.resource
  packages-to-exclude: net.axelwulff.usermanagement.repository
  show-actuator: true
